SocialDistribution/myapp/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views
from .views import NewPostView, PostListView, PostDetailView, PostEditView, PostDeleteView, SharedPostView, ShareDetailView, friendRequests, acceptFriendRequest

app_name = 'myapp'
urlpatterns = [
    # ex: /polls/
    # path('feed/', views.feed, name='feed'),
    path('newpost/', NewPostView.as_view(), name='newpost'),
    # path('feed/', views.search),
    path('feed/',PostListView.as_view(), name='postList'),
    path('post/<uuid:pk>',PostDetailView.as_view(), name='postDetail'),
    path('post/edit/<uuid:pk>',PostEditView.as_view(), name='postEdit'),
    path('post/delete/<uuid:pk>',PostDeleteView.as_view(), name='postDelete'),
    path('authors/<str:user_id>', views.profile, name='profile'),
    path('follow', views.follow, name='follow'),
    path('friendRequests', friendRequests, name='friendRequests'),
    path('acceptFriendRequest/<actor_id>', acceptFriendRequest, name='acceptFriendRequest'),
    path('like', views.like, name='like'),
    path('liked/<uuid:post_id>', views.liked, name='liked'),
    path('post/<uuid:pk>/share', SharedPostView.as_view(), name='sharePost'),
    path('post/shared/<uuid:pk>',ShareDetailView.as_view(), name='shareDetail'),
    path('', views.getuser, name='getuser'),
]

SocialDistribution/myapp/templates/feed.html
{% extends 'base.html' %}

{% block title %}Feed{% endblock %}

{% block content %}

    {% if user.is_authenticated %}

    {% load static %}

    {% load markdownify %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/feed.css' %}">

    <div class="colContainer">

        {% include "sidebarLeft.html" %}

        <div class="middle">
            <div id="postDiv">
                <form action="{% url 'myapp:newpost' %}">
                    <input id="postBar" type="submit" value="What's on your mind?">
                </form>
                <div id="prompt">
                    <h3>Let's post something!</h3>
                </div>
            </div>
            <div id="postHolder">
                <!-- <div class="singlePost">
                                                        <div class="authorName">{name}</div>
                                                        <div class="postTitle">Title</div>
                                                        <div class="postBody">body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...body...</div>
                                                        <div class="postTime">2022-02-19 2:14PM<div class="postVis">Visibility: Public</div></div>
                                                        <div class="postActions"><a href="google.com"><i class="fa-solid fa-share"></i>&ensp;Share</a>&emsp;<a href="google.com"><i class="fa-solid fa-heart"></i>&ensp;Like</a>&emsp;<a href="google.com"><i class="fa-solid fa-comment"></i>&ensp;Comment&emsp;</a></div>
                                                    </div> -->
                <!-- Reference: https://stackoverflow.com/questions/6540032/sorting-related-items-in-a-django-template -->
                <!-- https://docs.djangoproject.com/en/dev/ref/templates/builtins/#std:templatefilter-dictsort -->
                {% comment %} {% for post in postList.all|dictsortreversed:"published"%} {% endcomment %}
                {% for post in postList %}
                    <div class="singlePost position-relative">
                        {% if post.type == 'share'%}
                            <!-- <div class="postActions" style="text-align: left; color: black;"> <span style="font-weight: bold; color: #F28482; font-size: 18px;">{{post.author.username}}</span> shared post from <a a style="color: rgb(135, 172, 228); font-style: italic; font-size: 15px;" href="{{post.source}}">{{post.source}}</a></div> -->
                            <div class="postBody" style="text-align: left; color: black;"> <span style="font-weight: bold; color: #F28482; font-size: 18px;">{{post.author.username}}</span> shared a post.</div>
                            <div class="postBody">Share note: {{post.title}}</div>
                            <div class="postBody" style="color: #F28482; background-color: #d5d5d584; margin-left: 5%;">Original Post Content:<br>{{post.content}}</div>
                            <!-- <div class="postActions" style="float: left; margin-left: 7%; font-size: 12px;"><a style="color: rgb(135, 172, 228); font-style: italic;" href="{{ post.origin }}">link to the original post</a></div> -->
                        {% else %}
                            <div class="authorName">Author: {{ post.author.username }}</div>
                            <div class="postTitle">{{ post.title }}</div>
                            <!-- pip install django-markdownify -->
                            {% if post.contentType == "text/markdown" %}
                                <div class="postBody">{{ post.content | markdownify}}</div>
                            {% else %}
                                <div class="postBody">{{ post.content}}</div>
                            {% endif %}
                            {% if post.post_image %}
                                <img src="{{ post.post_image.url }}" width="100%">
                            {% endif %}
                        {% endif %}
                        <div class="postTime">{{ post.published }}
                            <div class="postVis">Visibility: {{ post.visibility }}</div>
                        </div>
                        <!-- <div>UUID: {{ post.id }}</div> -->
                        <div class="postActions"><a href="{% url 'myapp:sharePost' post.uuid %}"><i class="fa-solid fa-share"></i>&ensp;Share</a>&emsp;<a
                                href="/like?post_id={{post.uuid}}"><i class="fa-solid fa-heart"></i>&ensp;{{post.likes}}</a>&emsp;<a
                                href="{% url 'myapp:postDetail' post.uuid %}"><i class="fa-solid fa-comment"></i>&ensp;{{ post.count }}&emsp;</a>
                        </div>
                        {% if post.type == 'post'%}
                        <a href="{% url 'myapp:postDetail' post.uuid %}" class="stretched-link"></a>
                        {% else %}
                        <a href="{% url 'myapp:shareDetail' post.uuid %}" class="stretched-link"></a>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
        {% include "sidebarRight.html" %}
    </div>

    {% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
    {% endif %}
{% endblock %}

SocialDistribution/myapp/templates/friendRequests.html
{% extends 'base.html' %}

{% block title %}Feed{% endblock %}

{% block content %}

    {% if user.is_authenticated %}

    {% load static %}

    {% load markdownify %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/feed.css' %}">

    <div class="colContainer">

        {% include "sidebarLeft.html" %}

        <div class="middle">
            <div id="postHolder">
                {% for friendRequest in friendRequests%}
                    <div class="singlePost position-relative">
                            <!-- <div class="postActions" style="text-align: left; color: black;"> <span style="font-weight: bold; color: #F28482; font-size: 18px;">{{post.author.username}}</span> shared post from <a a style="color: rgb(135, 172, 228); font-style: italic; font-size: 15px;" href="{{post.source}}">{{post.source}}</a></div> -->
                            <div class="postBody" style="font-weight: bold; color: #F28482; font-size: 18px;">{{friendRequest.summary}}</div>
                            <form action="{% url 'myapp:acceptFriendRequest' friendRequest.actor.username %}">
                                <button type="submit" id="follow_request_button">Accept</button>
                            </form>
                            <!-- pip install django-markdownify -->
            
                        <!-- <div>UUID: {{ post.id }}</div> -->
                    </div>
                {% endfor %}
            </div>
        </div>
        {% include "sidebarRight.html" %}
    </div>

    {% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
    {% endif %}
{% endblock %}

SocialDistribution/myapp/templates/liked.html
{% extends 'base.html' %}

{% block title%}Post Detail{% endblock %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/postDetail.css' %}">
    <body>
        <div class="colContainer">
            {% include "sidebarLeft.html" %}
            <div class="column middle">
                <div>
                    <a href="{% url 'myapp:postList' %}" class="btn btn-light"> Back To Feed </a>                  
                </div>
                <div>
                    <div class="postTitle">
                        Liked By
                    </div>
                    {% for like in likes_list %}
                    <div> 
                        <div class="postBody" style="font-size: larger;">{{ like.author.username }}</div>                 
                    </div>                   
                    {% endfor %}
                </div>
            </div>
            {% include "sidebarRight.html" %}
        </div>

{% endblock %}

SocialDistribution/myapp/templates/newpost.html
{% extends 'base.html' %}

{% block title%}New Post{% endblock %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/newpost.css' %}">
    <body>
        <div class="colContainer">
            {% include "sidebarLeft.html" %}
            <div class="column middle">
                <div>
                    <div>
                        <a href="{% url 'myapp:postList' %}" class="btn btn-light"> Back To Feed </a>                  
                    </div>
                    <div id="newPostContainer">
                        <div class="poster-font logo-color" id="newPostText">New Post</div>
                        <hr>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- {{ form.as_table }} -->
                            <div class="postDetail">
                                <!-- <label for="title">Title:</label> -->
                                {{ form.title }}
                            </div>
                            <div class="postDetail">
                                <!-- <label for="description">Description:</label> -->
                                {{ form.description }}
                            </div>
                            <div class="postDetail">
                                <!-- <label for="description">Description:</label> -->
                                {{ form.content }}
                            </div>
                            <div class="postDetail">
                                <label for="contentType">Content Type:</label>
                                {{ form.contentType }}
                            </div>
                            <div class="postDetail">
                                <!-- <label for="description">Description:</label> -->
                                {{ form.unparsedCategories }}
                            </div>                           
                            <div class="postDetail">
                                <!-- <label for="visibility">Visibility:</label> -->
                                {{ form.visibility }}
                            </div>
                            <div class="postDetail">
                                {{ form.post_image }}
                            </div>
                            <div class="postDetail">
                                <button class="btnShare">Share</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% include "sidebarRight.html" %}
        </div>

        {% endblock %}

SocialDistribution/myapp/templates/postDelete.html
{% extends 'base.html' %}

{% block title%}New Post{% endblock %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/newpost.css' %}">
    <body>
        <div class="colContainer">
            {% include "sidebarLeft.html" %}
            <div class="column middle">
                <div>
                    <div>
                        <a href="{% url 'myapp:postDetail' object.uuid %}" class="btn btn-light"> Back To Post </a>                  
                    </div>
                    <div id="delPostContainer" class="singlePost">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="poster-font logo-color" id="newPostText">Delete This Post?</div>    
                                                 
                            <div class="postDetail">
                                <!-- <p>You are about to delete this post.</p>   -->
                                <button class="btnShare">Yes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% include "sidebarRight.html" %}
        </div>

        {% endblock %}

SocialDistribution/myapp/templates/postDetail.html
{% extends 'base.html' %}

{% block title%}Post Detail{% endblock %}

{% block content %}
{% load static %}
{% load markdownify %}

<link rel="stylesheet" type="text/css" href="{% static 'css/postDetail.css' %}">
    <body>
        <div class="colContainer">
            {% include "sidebarLeft.html" %}
            <div class="column middle">
                <div>
                    <a href="{% url 'myapp:postList' %}" class="btn btn-light"> Back To Feed </a>                  
                </div>
                <div>
                    <div class="singlePost">
                        <div class="postTitle">{{ post.title }}</div> 
                        {% if request.user.username == post.author.username %}
                            <a href="{% url 'myapp:postEdit' post.uuid %}"><i class="fa-solid fa-pen-to-square"></i></a>
                            <a href="{% url 'myapp:postDelete' post.uuid %}"><i class="fa-solid fa-trash-can"></i></a>
                        {% endif%}

                        
                        {% if post.contentType == "text/markdown" %}
                                <div class="postBody">{{ post.content | markdownify}}</div>
                            {% else %}
                                <div class="postBody">{{ post.content }}</div>
                        {% endif %}

                        
                        <!-- <div class="postBody">Categories: {{ post.categories }}</div> -->
                        <!-- <div class="postBody">{{ post.contentType }}</div> -->
                        <!-- <div class="postBody">{{ post.count }}</div> -->
                        <div class="postBody">
                            {% if post.post_image %}
                                <img src="data:image/jpg;base64, {{ image_b64 }}" width=100%>
                            {% endif %}
                            
                        </div>
                        <div class="postBody">
                            {% for category in post.categories.all %}
                                <span class="badge bg-secondary">{{ category.cat }}</span>
                            {% endfor %}
                        </div>

                        <div class="postTime">{{ post.published }}
                            <div class="postVis">Visibility: {{ post.visibility }}</div>
                        </div>


                        <div class="postActions">
                            
                            <a href="{% url 'myapp:sharePost' post.uuid %}"><i class="fa-solid fa-share"></i>&ensp;Share</a>&emsp;
                            <a href="{% url 'myapp:liked' post.uuid %}"><i class="fa-solid fa-heart"></i>&ensp;Likes</a>&emsp;
                            <a href="{% url 'myapp:postDetail' post.uuid %}"><i class="fa-solid fa-comment"></i>&ensp;{{ post.count }}&emsp;</a></div>                       
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <!-- {{ form.as_table }} -->
                        <div class="postDetail">
                            <!-- <label for="title">Title:</label> -->
                            {{ form.comment }}
                        </div>
                        <div class="postDetail">
                            <!-- <label for="title">Title:</label> -->
                            {{ form.contentType }}
                        </div>
                        <div class="postDetail">
                            <button class="btnShare">Share</button>
                        </div>
                    </form>
                    {% for comment in comments %}
                    <div class="singlePost position-relative"> 
                        <div class="postBody">{{ comment.author.username }}</div>
                        {% if post.contentType == "text/markdown" %}
                            <div class="postBody">{{ comment.comment | markdownify}}</div>
                        {% else %}
                            <div class="postBody">{{ comment.comment }}</div>
                        {% endif %}
                        <div class="postTime">{{ comment.published }}</div>                       
                    </div>                   
                    {% endfor %}
                </div>
            </div>
            {% include "sidebarRight.html" %}
        </div>

        {% endblock %}

SocialDistribution/myapp/templates/postEdit.html
{% extends 'base.html' %}

{% block title%}New Post{% endblock %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/newpost.css' %}">
    <body>
        <div class="colContainer">
            {% include "sidebarLeft.html" %}
            <div class="column middle">
                <div>
                    <div>
                        <a href="{% url 'myapp:postDetail' object.uuid %}" class="btn btn-light"> Back To Post </a>                  
                    </div>
                    <div id="newPostContainer">
                        <div class="poster-font logo-color" id="newPostText">Update Post</div>
                        <hr>
                        <form method="POST">
                            {% csrf_token %}
                            <!-- {{ form.as_table }} -->
                            <div class="postDetail">
                                <!-- <label for="title">Title:</label> -->
                                {{ form.title }}
                            </div>
                            <div class="postDetail">
                                <!-- <label for="description">Description:</label> -->
                                {{ form.content }}
                            </div>
                            <div class="postDetail">
                                <label for="contentType">Content Type:</label>
                                {{ form.contentType }}
                            </div>
                            <div class="postDetail">
                                <!-- <label for="description">Description:</label> -->
                                {{ form.categories }}
                            </div>
                            <div class="postDetail">
                                <label for="visibility">Visibility:</label>
                                {{ form.visibility }}
                            </div>
                            <div class="postDetail">
                                <button class="btnShare">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% include "sidebarRight.html" %}
        </div>

        {% endblock %}

SocialDistribution/myapp/templates/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

    <link rel="stylesheet" href="https://unpkg.com/github-calendar@latest/dist/github-calendar-responsive.css"/>
   
   <style>
        #follow_request_button {
            background-color: #ffc0cb; 
            border: #ffc0cb;
            margin-left: 10%;
        }
    </style>

    <div class="colContainer">
        {% include "sidebarLeft.html" %}
        <div class="column middle">
            <div class="add-btn">
                <!-- <img>{{ current_author_info.profileImage }}</a></img> -->
                <!-- <img scr="../images/avatar1.jpg", alt="user avatar", class="avatar"> -->
                <form action="{% url 'myapp:follow' %}" method="POST">
                    {% csrf_token %}
                    <img style="width: 25%;" src="{{ current_author_info.profileImage }}"
                         class='avatar'/>
                    <div class="userInfo">user id: {{ current_author_info.username }}</div>
                    <div class="userInfo">name: {{ current_author_info.displayName }}</div>
                    <!-- <button class="followerButton">Follower</button> -->
                    <!-- <a href="#" class="followButton">Follower</a> -->
                    <span class="userInfo" style="padding: left;"><b>{{ count_followers }}  Followers</b></span>
                    <input type="hidden" value="{{ user.username }}" name="follower"/>
                    <input type="hidden" value="{{ current_author_info.username }}" name="user"/>
                    {% if current_author_info.username == user.username %}
                        <a href="" data-ripple="">Edit Account</a>
                    {% else %}
                        <a data-ripple="">
                            <button type="submit" id="follow_request_button">{{ button_text }}</button>
                        </a>
                        <!-- {% include 'sendFriendRequest.html' %}
                        <script type="text/javascript">
                            function onFriendRequestSent(){
                                location.reload();
                            }
                            // print("!!!!!!!!\n", 'id not match', '!!!!!!!!!!\n')
                            var sendFriendRequestBtn = document.getElementById("follow_request_button")
                            //if (sendFriendRequestBtn == null){
                                //print("!!!!!!!!\n", 'id not match', '!!!!!!!!!!\n')
                            sendFriendRequestBtn.addEventListener("click", function(){
                                sendFriendRequest("suzihan", onFriendRequestSent)
                            })
                            //}
                        </script> -->
                    {% endif %}
                </form>
                <!-- <button class="followerButton">Following</button> -->
                <div class="userInfo">github info: {{ current_author_info.github }}</a></div>

                <!-- reference: https://github.com/Bloggify/github-calendar -->
                <!-- Optionally, include the theme (if you don't want to struggle to write the CSS) -->
                <script src="https://cdn.rawgit.com/IonicaBizau/github-calendar/gh-pages/dist/github-calendar.min.js"></script>
                <br>
                <i class="fa fa-github" style="font-size:36px;"></i>
                <br>
                <a style="font-size: 20px;">Github Activity</a>
                <p>{{ github_username }}</p>

                <div class="calendar">
                    <!-- Loading stuff -->
                    <img src="https://github.githubassets.com/images/spinners/octocat-spinner-128.gif" class="spinner"/>
                    Loading the data just for you. If it doesn't show up, the github URL may be wrong.
                </div>

                <script>
                    new GitHubCalendar(".calendar", "{{ github_username }}");
                    var calendar = document.getElementsByClassName("calendar");
                    calendar[0].style.border = "none";
                </script>

                {% for post in posts %}
                    <div class="singlePost position-relative">
                    {% if post.type == 'share'%}
                        <div class="postActions" style="text-align: left; color: black;"> 
                            <span style="font-weight: bold; color: #F28482; font-size: 18px;">
                                {{post.author.id}}
                            </span> 
                            shared post from 
                            <a a style="color: rgb(135, 172, 228); font-style: italic; font-size: 15px;" href="{{post.source}}">
                                {{post.source}}
                            </a></div>
                        <div class="postBody">Share note: {{post.title}}</div>
                         <div class="postBody" style="color: #F28482; background-color: #d5d5d584; margin-left: 5%;">Original Post Content:<br>{{post.description}}</div>
                        <div class="postActions" style="float: left; margin-left: 7%; font-size: 12px;">
                            <a style="color: rgb(135, 172, 228); font-style: italic;" href="{{ post.origin }}">link to the original post</a></div>
                    
                    {% else %}
                        <div class="authorName">Author: {{ post.author.username }}</div>
                        <div class="postTitle">{{ post.title }}</div>
                        <div class="postBody">{{ post.description }}</div>
                    {% endif %}    
                        <div class="postTime">{{ post.published }}
                            <div class="postVis">Visibility: {{ post.visibility }}</div>
                        </div>
                        <div>UUID: {{ post.id }}</div>
                        <div class="postActions"><a href="{% url 'myapp:sharePost' post.uuid %}"><i class="fa-solid fa-share"></i>&ensp;Share</a>&emsp;<a
                                href="/like?post_id={{post.uuid}}"><i class="fa-solid fa-heart"></i>&ensp;{{post.likes}}</a>&emsp;<a
                                href="{% url 'myapp:postDetail' post.uuid %}"><i class="fa-solid fa-comment"></i>&ensp;{{ post.count }}&emsp;</a>
                        </div>
                        {% if post.type == 'post'%}
                        <a href="{% url 'myapp:postDetail' post.uuid %}" class="stretched-link"></a>
                        {% else %}
                        <a href="{% url 'myapp:shareDetail' post.uuid %}" class="stretched-link"></a>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
        {% include "sidebarRight.html" %}
    </div>
{% endblock %}

SocialDistribution/myapp/templates/shareDetail.html
{% extends 'base.html' %}

{% block title%}Post Detail{% endblock %}

{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/postDetail.css' %}">
    <body>
        <div class="colContainer">
            {% include "sidebarLeft.html" %}
            <div class="column middle">
                <div>
                    <a href="{% url 'myapp:postList' %}" class="btn btn-light"> Back To Feed </a>                  
                </div>
                <div>
                    <div class="singlePost">                      
                        <div class="postBody" style="font-size: 25px; font-weight: bold;">{{ post.author.username }} <span style="font-size: medium;">shared with comments:</span><br>
                        {{post.title}}</div> 
                        {% if request.user.username == post.author.username %}
                            <a href="{% url 'myapp:postEdit' post.uuid %}"><i class="fa-solid fa-pen-to-square"></i></a>
                            <a href="{% url 'myapp:postDelete' post.uuid %}"><i class="fa-solid fa-trash-can"></i></a>
                        {% endif%}
                            <div class="postBody">
                                <div class="singlePost" style="background-color: rgba(193, 199, 201, 0.283); margin-left: 6%; margin-top: 0%; border-radius: 4%;">   
                                    <div class="authorName" style="left: 2%; text-indent: 0%;" >{{source_post.author.username}}</div>                   
                                    <div class="postTitle">{{ source_post.title }}</div> 
                                        <div class="postBody">{{ source_post.content }}</div>
                                    <div class="postTime" style="font-size: small;">{{ source_post.published }}<div class="postVis" style="font-size: 12px;">Visibility: {{ post.visibility}}</div></div>  
                                </div>
                            </div>
                        <div>
                            <div class="postActions" style="float: left; margin-left: 7%; font-size: 12px;"><a style="color: rgb(135, 172, 228); font-style: italic;" href="{% url 'myapp:postDetail' original_post.uuid %}">link to the original post</a></div> 
                        </div>      
                        <div class="postTime">{{ post.published }}<div class="postVis">Visibility: {{ post.visibility}}</div></div>  
                        <div class="postActions"><a href="{% url 'myapp:sharePost' post.uuid %}"><i class="fa-solid fa-share"></i>&ensp;Share</a>&emsp;
                            <a href="{% url 'myapp:liked' post.uuid %}"><i class="fa-solid fa-heart"></i>&ensp;Likes</a>&emsp;
                            <a href="{% url 'myapp:postDetail' post.uuid %}"><i class="fa-solid fa-comment"></i>&ensp;{{ post.count }}&emsp;</a></div>                       
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <!-- {{ form.as_table }} -->
                        <div class="postDetail">
                            <!-- <label for="title">Title:</label> -->
                            {{ form.comment }}
                        </div>
                        <div class="postDetail">
                            <button class="btnShare">Share</button>
                        </div>
                    </form>
                    {% for comment in comments %}
                    <div class="singlePost position-relative"> 
                        <div class="postBody">{{ comment.author.username }}</div>
                        <div class="postBody">{{ comment.comment }}</div>
                        <div class="postTime">{{ comment.published }}</div>                       
                    </div>                   
                    {% endfor %}
                </div>
            </div>
            {% include "sidebarRight.html" %}
        </div>

        {% endblock %}